# Generated by Django 3.1.2 on 2020-10-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20201020_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_ex',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='pic',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='nutritionFacts_ex',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
