# Generated by Django 3.1.2 on 2020-10-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20201020_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritionfacts',
            name='food',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='NutritionFacts',
        ),
    ]
